@echo off
setlocal
chcp 65001 >nul
REM STEREO Vibe Lite launcher. GENERATED by build.py - edit the template there.
REM Keep this file ASCII-only and CRLF: cmd.exe parses .cmd in the OEM codepage,
REM Cyrillic bytes here break parsing. All Russian text lives in the .ps1
REM (the "no core folder" message below is a base64 -EncodedCommand for that reason).
REM The service folder has a Cyrillic name, so it is located by the script it
REM contains, not by a name written here.
REM   launcher             - check and install (asks for admin rights)
REM   launcher /check      - check only: nothing is installed, no admin rights

set "PS=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"
set "CORE="
for /d %%D in ("%~dp0*") do if exist "%%~fD\check-work-tools.ps1" set "CORE=%%~fD"
if not defined CORE goto :nocore
if /i "%~1"=="/check" goto :check

REM --- Admin rights: without them winget installs can die halfway. -----------
REM Ask for elevation via UAC up front; if declined, continue with a warning.
net session >nul 2>nul
if %errorlevel% equ 0 goto :admin_ok
echo.
echo   Requesting administrator rights (needed to install programs)...
echo   Click "Yes" if Windows asks.
echo.
if "%~1"=="" (
  "%PS%" -NoProfile -Command "try { Start-Process -FilePath '%~f0' -Verb RunAs -ErrorAction Stop } catch { exit 1 }"
) else (
  "%PS%" -NoProfile -Command "try { Start-Process -FilePath '%~f0' -ArgumentList '%*' -Verb RunAs -ErrorAction Stop } catch { exit 1 }"
)
if %errorlevel% equ 0 exit /b 0
echo.
echo   Rights not granted - continuing WITHOUT them.
echo   Installing programs may fail.
echo.

:admin_ok
REM Force Windows PowerShell 5.1: Appx cmdlets (Get-AppxPackage) fail in PowerShell 7.
"%PS%" -NoProfile -ExecutionPolicy Bypass -File "%CORE%\check-work-tools.ps1" %*
exit /b %ERRORLEVEL%

:check
"%PS%" -NoProfile -ExecutionPolicy Bypass -File "%CORE%\check-work-tools.ps1" -ReportOnly %2 %3 %4 %5 %6
exit /b %ERRORLEVEL%

:nocore
"%PS%" -NoProfile -EncodedCommand VwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACAAIAAdBDUEIAA9BDAERQQ+BDYEQwQgAEEEOwRDBDYENQQxBD0EQwROBCAAPwQwBD8EOgRDBCAAPwQwBDoENQRCBDAELgAnACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAFkAZQBsAGwAbwB3AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACAAIAAhBD0EMARHBDAEOwQwBCAAQAQwBEEEPwQwBDoEQwQ5BCAAMARABEUEOAQyBDoAIAA/BEAEMAQyBEsEOQQgADoEOwQ4BDoEIAA/BD4EIABzAHQAZQByAGUAbwB2AGkAYgBlAC0AbABpAHQAZQAuAHoAaQBwACAALQA+ACAAqwAYBDcEMgQ7BDUERwRMBCAAMgRBBFEEuwAsACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAWQBlAGwAbABvAHcACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAgACAAPwQ+BEIEPgQ8BCAAPgRCBDoEQAQ+BDkEIABABDAEQQQ/BDAEOgQ+BDIEMAQ9BD0EQwROBCAAPwQwBD8EOgRDBCAAOAQgADcEMAQ/BEMEQQRCBDgEIACrABcEMAQ/BEMEQQRCBDgEQgRMBCAAVgBpAGIAZQAuAGMAbQBkALsAIAA+BEIEQgRDBDQEMAQuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAAWQBlAGwAbABvAHcACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAnAAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAIAAgABUEQQQ7BDgEIAAwBEAERQQ4BDIEIABDBDYENQQgAEAEMARBBD8EMAQ6BD4EMgQwBD0EOgAgAD8EMAQ/BDoEMAQgAKsAXwA9BDUEIABCBEAEPgQzBDAEQgRMBLsAIAA0BD4EOwQ2BD0EMAQgADsENQQ2BDAEQgRMBCAAQARPBDQEPgQ8BCAAQQQgAE0EQgQ4BDwEIABEBDAEOQQ7BD4EPAQuACcAIAAtAEYAbwByAGUAZwByAG8AdQBuAGQAQwBvAGwAbwByACAARABhAHIAawBHAHIAYQB5AAoAVwByAGkAdABlAC0ASABvAHMAdAAgACcAIAAgACMENAQwBDsEOAQ7BCAAOAQ7BDgEIAA/BDUEQAQ1BD0EUQRBBCAANQRRBCAAFCAgAEEEOgQwBEcEMAQ5BCAAMARABEUEOAQyBCAANwQwBD0EPgQyBD4ELgAnACAALQBGAG8AcgBlAGcAcgBvAHUAbgBkAEMAbwBsAG8AcgAgAEQAYQByAGsARwByAGEAeQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACcACgA=
pause
exit /b 3
